# Generated by Django 4.2.1 on 2023-05-20 02:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hospital", "0003_alter_hospital_latitude"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hospital",
            name="latitude",
            field=models.FloatField(
                validators=[
                    django.core.validators.MinValueValidator(-90.0),
                    django.core.validators.MaxValueValidator(90.0),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="hospital",
            name="longitude",
            field=models.FloatField(
                validators=[
                    django.core.validators.MinValueValidator(-180.0),
                    django.core.validators.MaxValueValidator(180.0),
                ]
            ),
        ),
    ]
